FROM golang:1.21.2

WORKDIR /app

COPY payment-service/go.mod payment-service/go.sum ./

RUN go mod download

COPY shared/proto/ ./proto/

COPY payment-service/ ./

RUN go build -o main .

EXPOSE 50051

CMD ["/app/main"]