FROM golang:1.21.2

WORKDIR /app

COPY user-service/go.mod user-service/go.sum ./

RUN go mod download

COPY shared/proto/ ./proto/

COPY user-service/ ./

RUN go build -o main .

EXPOSE 50051

CMD ["/app/main"]